// Test generated by RoostGPT for test PizzaShop using AI Type Open AI and AI Model gpt-4

const { JSDOM } = require("jsdom");

describe("hideModal function", () => {
  let dom, window, document, modal;

  beforeEach(() => {
    dom = new JSDOM(`<!DOCTYPE html><div class="modal on"></div>`);
    window = dom.window;
    document = window.document;
    modal = document.querySelector(".modal");
    global.document = document;
    global.window = window;
  });

  afterEach(() => {
    jest.resetModules();
  });

  test("should remove 'on' class and add 'off' class when event is not passed", () => {
    const hideModal = require('./main').hideModal;
    hideModal();
    expect(modal.classList.contains("on")).toBe(false);
    expect(modal.classList.contains("off")).toBe(true);
    expect(modal.classList.contains("offout")).toBe(false);
  });

  test("should remove 'on' and 'off' classes and add 'offout' class when event is passed", () => {
    const hideModal = require('./main').hideModal;
    const e = { preventDefault: jest.fn() };
    hideModal(e);
    expect(e.preventDefault).toHaveBeenCalled();
    expect(modal.classList.contains("on")).toBe(false);
    expect(modal.classList.contains("off")).toBe(false);
    expect(modal.classList.contains("offout")).toBe(true);
  });
});
