// Test generated by RoostGPT for test PizzaShop using AI Type Open AI and AI Model gpt-4

const { JSDOM } = require('jsdom');
const fs = require('fs');
const path = require('path');
const main = fs.readFileSync(path.resolve(__dirname, './main.js'), 'utf8');

let dom;
let container;

describe('showModal function', () => {
  beforeAll(() => {
    dom = new JSDOM(main, { runScripts: 'dangerously' });
  });

  beforeEach(() => {
    container = dom.window.document.createElement('div');
    container.innerHTML = `
      <div class="modal off">
        <div id="infotype"></div>
        <div id="idtype"></div>
        <div id="msgStt"></div>
        <div id="msgCod"></div>
        <div id="msgTit"></div>
        <div id="msgDet"></div>
      </div>
    `;
    dom.window.document.body.appendChild(container);
  });

  afterEach(() => {
    dom.window.document.body.removeChild(container);
  });

  it('should display the modal with provided message', () => {
    dom.window.showModal({ title: 'Error', class: 'error' }, '404', 'ERR001', 'Not Found', 'The requested resource was not found.');

    expect(dom.window.document.querySelector('.modal').classList).toContain('on');
    expect(dom.window.document.querySelector('#infotype').className).toBe('error');
    expect(dom.window.document.querySelector('#idtype').textContent).toBe('Error');
    expect(dom.window.document.querySelector('#msgStt').textContent).toBe('404');
    expect(dom.window.document.querySelector('#msgCod').textContent).toBe('ERR001');
    expect(dom.window.document.querySelector('#msgTit').textContent).toBe('Not Found');
    expect(dom.window.document.querySelector('#msgDet').textContent).toBe('The requested resource was not found.');
  });

  it('should throw an error when modal element is not found', () => {
    dom.window.document.querySelector('.modal').remove();

    expect(() => {
      dom.window.showModal({ title: 'Error', class: 'error' }, '404', 'ERR001', 'Not Found', 'The requested resource was not found.');
    }).toThrow();
  });
});
