// Test generated by RoostGPT for test PizzaShop using AI Type Open AI and AI Model gpt-4

const { JSDOM } = require("jsdom");
const dom = new JSDOM();
global.document = dom.window.document;

const { updateMenu } = require('./main');

describe('updateMenu', () => {
  let submenu1, submenu2, adminHide, mnAdminSi, mnChgpwd;

  beforeAll(() => {
    submenu1 = document.createElement('div');
    submenu1.classList.add('submenu');
    document.body.appendChild(submenu1);

    submenu2 = document.createElement('div');
    submenu2.classList.add('submenu');
    document.body.appendChild(submenu2);

    adminHide = document.createElement('div');
    adminHide.id = 'admin-hide';
    document.body.appendChild(adminHide);

    mnAdminSi = document.createElement('div');
    mnAdminSi.id = 'mn-admin-si';
    document.body.appendChild(mnAdminSi);

    mnChgpwd = document.createElement('div');
    mnChgpwd.id = 'mn-chgpwd';
    document.body.appendChild(mnChgpwd);
  });

  test('should toggle hide class for submenu and admin-hide, and add event listener to mn-chgpwd', () => {
    updateMenu();
    expect(submenu1.classList.contains('hide')).toBe(true);
    expect(submenu2.classList.contains('hide')).toBe(true);
    expect(adminHide.classList.contains('hide')).toBe(true);
    expect(mnAdminSi.classList.contains('hide')).toBe(false);
    expect(mnChgpwd.onclick).toBeDefined();
  });

  test('should toggle hide class again for submenu and admin-hide, and mn-chgpwd should still have event listener', () => {
    updateMenu();
    expect(submenu1.classList.contains('hide')).toBe(false);
    expect(submenu2.classList.contains('hide')).toBe(false);
    expect(adminHide.classList.contains('hide')).toBe(false);
    expect(mnAdminSi.classList.contains('hide')).toBe(true);
    expect(mnChgpwd.onclick).toBeDefined();
  });
});
